name: openGA package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt 
          
      - name: Running tests
        run: |
          set -e
          python --version
          python -m pytest -vv --color=yes --disable-pytest-warnings --cov-report xml:coverage.xml --cov=openGA/ test/
          
